# Generated by Django 4.2.29 on 2026-03-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Restoran Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('address', models.CharField(max_length=250, verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('price_range', models.CharField(choices=[('€', 'Ucuz'), ('€€', 'Orta'), ('€€€', 'Pahalı')], max_length=5, verbose_name='Fiyat Aralığı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.category', verbose_name='Kategori')),
            ],
        ),
    ]
